//App Store
export const SET_PIZZA_PARAMS = "SET_PIZZA_PARAMS";

// Builder Store
export const SET_DEFAULT_CURRENT_PIZZA = "SET_DEFAULT_CURRENT_PIZZA";
export const SET_CURRENT_PIZZA = "SET_CURRENT_PIZZA";
export const SET_CURRENT_PIZZA_NAME = "SET_CURRENT_PIZZA_NAME";
export const SET_CURRENT_DOUGH_TYPE = "SET_CURRENT_DOUGH_TYPE";
export const SET_CURRENT_SAUCE = "SET_CURRENT_SAUCE";
export const SET_CURRENT_SIZE = "SET_CURRENT_SIZE";
export const INC_INGREDIENT_COUNT_BY_ID = "INC_INGREDIENT_COUNT_BY_ID";
export const DEC_INGREDIENT_COUNT_BY_ID = "DEC_INGREDIENT_COUNT_BY_ID";

//Card
export const SET_ALL_ADDITION_PRODUCTS = "SET_ALL_ADDITION_PRODUCTS";
export const ADD_PIZZA_TO_PIZZA_LIST = "ADD_PIZZA_TO_PIZZA_LIST";
export const SET_COUNT_OF_PIZZA = "SET_COUNT_OF_PIZZA";
export const SET_COUNT_OF_ADDITION_PRODUCT = "SET_COUNT_OF_ADDITION_PRODUCT";
