export const SET_PIZZA_PARAMS = "SET_PIZZA_PARAMS";
export const SET_CURRENT_PIZZA_NAME = "SET_CURRENT_PIZZA_NAME";
export const SET_CURRENT_DOUGH_TYPE = "SET_CURRENT_DOUGH_TYPE";
export const SET_CURRENT_SAUCE = "SET_CURRENT_SAUCE";
export const SET_CURRENT_SIZE = "SET_CURRENT_SIZE";
export const INC_INGREDIENT_COUNT_BY_ID = "INC_INGREDIENT_COUNT_BY_ID";
export const DEC_INGREDIENT_COUNT_BY_ID = "DEC_INGREDIENT_COUNT_BY_ID";
